export const SET_CONTACTS = "CONTACTS/SET-CONTACTS";
export const ADD_CONTACT = "CONTACTS/ADD-CONTACT";
export const EDIT_CONTACT = "CONTACTS/EDIT-CONTACT";
export const DELETE_CONTACT = "CONTACTS/DELETE-CONTACT";
